[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Scheduled function (every 15 min, UTC)
[[scheduled.functions]]
  function = "reminders-cron"
  cron = "*/15 * * * *"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[functions."stripe-webhook"]
  external_node_modules = ["stripe"]

[build.environment]
  NODE_VERSION = "20"

