[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Scheduled function (every 5 min, UTC)
[[scheduled.functions]]
  function = "reminders-cron"
  cron = "*/15 * * * *"
