[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ✅ Run reminder emails automatically every 2 minutes
[[scheduled.functions]]
  path = "reminders-cron"
  schedule = "*/2 * * * *"
