[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Run your scheduler every 5 minutes by function name (no extension needed)
[[scheduled.functions]]
  function = "reminders-cron"
  cron = "*/5 * * * *"

# Quiet the secret scanner for public keys
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_AMAZON_PARTNER_TAG,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"
