[build]
command = "npm run build"
publish = "dist"
ignore = "git diff --quiet HEAD^ HEAD -- ./src /functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[functions]]
name = "reminders-check"
schedule = "*/5 * * * *"

[[functions]]
name = "resend-self-test"

[[functions]]
name = "resend-smoke"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200