[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[scheduled.functions]]
  function = "reminders-cron"
  cron = "*/5 * * * *"

# Ignore specific public keys and Resend variables that trigger false positives
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_AMAZON_PARTNER_TAG,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,RESEND_FROM,RESEND_REPLY_TO"
