[build]
command = "npm run build"
publish = "dist"
ignore = "git diff --quiet HEAD^ HEAD -- ./src /functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# schedule reminders-check every 5 minutes
[[scheduled]]
path = "/.netlify/functions/reminders-check"
schedule = "*/5 * * * *"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
